### PR TITLE
Added Code of Conduct, License, ToC

### PR DESCRIPTION
**Pull request by RichardLitt**
Standardizes README a bit. Closes https://github.com/haadcode/ipfs-log/issues/1.

### CODE REVIEW

**Comment by haadcode** [comment]
Not a fan of the TOC. Let's remove that from this PR.

**Comment by RichardLitt** [comment]
@haadcode Can I have more of an explanation than that? What's wrong with the Table of Contents?

**Comment by haadcode** [comment]
It doesn't look nice in the readme, takes too much space/time in "show me the money" sense.

**Comment by RichardLitt** [comment]
Dude, it is super long.

**Comment by RichardLitt** [comment]
Ok, I cut down the ToC quite a bit. Can you check this again?

**Pull request merged**
